In [4]:
# Problem Statement
# Identify charges for insurance based on the metrics provided.
# After looking into the dataset its numerical data. 
# Both input and outputs are available.
# Output label is numerical.
###################################################
# Domain - MACHINE LEARNING
# Supervised Learning
# Regression
###################################################

In [5]:
import pandas as pd

In [6]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
# Dataset has 1338 Rows X 6 Columns
# We have to convert the following nominal fields to numerical using one-hot encoding.
# The nominal fields are smoker, sex.

In [8]:
# Preprocessing
dataset = pd.get_dummies(dataset, dtype="int64", drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [9]:
#  Display Columns
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [10]:
# Identify independent variables
independent = dataset[["age", "bmi", "children", "sex_male", "smoker_yes"]]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
# Identify dependent variable
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [ ]:
# Import GridSearchCV, which automatically tries different hyperparameter combinations
# and finds the combination that gives the best cross-validation score
from sklearn.model_selection import GridSearchCV

# Import Support Vector Regression algorithm
from sklearn.svm import SVR

# Define the hyperparameters and the values that we want GridSearchCV to try
param_grid = {
    # Try four different types of kernels
    'kernel': ['rbf', 'poly', 'sigmoid', 'linear'],

    # Try different values of C, which controls the trade-off between model complexity
    # and allowing errors
    'C': [10, 100, 1000, 2000, 3000],

    # Try both automatic and scaled calculations for gamma
    'gamma': ['auto', 'scale']
}

# Create the GridSearchCV object
# SVR() is the model we want to tune
# param_grid contains all the hyperparameter combinations to test
# refit=True means the best model will be trained again using the complete training data
# verbose=3 displays detailed information about the progress
# n_jobs=-1 uses all available CPU cores to speed up the search
grid = GridSearchCV(
    SVR(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)

# Run the hyperparameter search on the training data
# GridSearchCV trains and evaluates SVR for every combination in param_grid
grid.fit(independent, dependent)
print("completed")

Fitting 5 folds for each of 40 candidates, totalling 200 fits

In [ ]:
# Print best parameter after tuning
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)
table

In [ ]:
from sklearn.metrics import r2_score
grid_predictions = grid.predict(x_test)
r_score = r2_score(y_test, grid_predictions)
print("The R2 value for best params {}: ".format(grid.best_params_), r_score)

In [ ]:
# Print best parameter after tuning
re = grid.cv_results_
grid_predictions = grid.predict(x_test)
grid_predictions

In [ ]:
age = float(input("Age: "))
bmi = float(input("BMI: "))
children = float(input("Children: "))
sex = float(input("Sex Male 0 or 1: "))
smoker = float(input("Smoker Yes 0 or 1: "))
future_prediction = grid.predict(
    [[age, bmi, children, sex, smoker]]
)
future_prediction